services:
  nr_gnb:
    image: docker_ueransim
    container_name: nr_gnb
    env_file:
      - ../.env
    stdin_open: true
    volumes:
      - ../multi-gnb:/mnt/multi-gnb
      - ./ueransim_image_init.sh:/ueransim_image_init.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COMPONENT_NAME=ueransim-gnb
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_GNB_IP}
    # mem_limit: 256m
    # cpus: 1.0
networks:
  default:
    name: 5g-bridge
    external: true
